### ISSUE TITLE
Numpy support

### ISSUE THREAD

**Issue by SamWhited** [photoshell/rawkit#106]
We probably want to figure out a good way to support numpy without having a hard dependency on it.

**Comment by campaul** [comment]
Closing this because `tools/view_raw.py` already provides a good example of using numpy. It's a one liner.

**Comment by SamWhited** [comment]
Maybe that (and the stuff in the examples tree) could be copied into the docs under the tutorials section instead to make it more discoverable? (I'm not sure if that's actually more discoverable or not)
