### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by juanpablovega** [photoshell/rawkit#115]
Hi,

I'm using your module and I've been experiencing (severe) memory leaks when converting a raw folder. I solved it by adding a call to self.libraw_recycle(self.data) when I exit the context.

Hope this helps.

**Comment by campaul** [comment]
Thanks for the report.

Can you provide a code example that demonstrates the leak? The entire libraw structure should be getting freed when the context manager exits, so I'm not sure what exactly is going wrong. Seeing your code should help me reproduce the issue more quickly. Also if you know what version of libraw you have installed that would be good to know.

**Comment by campaul** [comment]
@juanpablovega I haven't been able to reproduce your issue. I'm currently converting 10,000 photos and my memory usage is remaining constant. Do you have a code example that I can use to reproduce the memory leak?
