### ISSUE TITLE
Issue with util.find_library('raw') when libraw installed directory other than /usr/local

### ISSUE THREAD

**Issue by wadawson** [photoshell/rawkit#119]
On some linux/unix operating systems (e.g. TOSS) the `ctypes.util.find_library()` function doesn't look in the `LD_LIBRARY_PATH` (see e.g., https://bugs.python.org/issue2936). This leads to a rawkit inability to find LibRaw installations that are installed in non-default directories (e.g. due to limited permissions I have to install LibRaw in a user directory like ~/local). Since [libraw/bindings.py](https://github.com/photoshell/rawkit/blob/master/libraw/bindings.py#L30-L38) uses `util.find_library('raw')` during `__init__`, rawkit will crash.

According to https://bugs.python.org/issue2936 it seems like the solution is to use something like:
1. Add your local library path where LibRaw is installed to `LD_LIBRARY_PATH`, e.g. `LD_LIBRARY_PATH=$HOME/local/lib`
2.  Use something like `ctypes.cdll.LoadLibrary("libraw.so")` in libraw/bindings.py instead of `ctypes.util.find_library('raw')`.

**Comment by wadawson** [comment]
I should have read some of the other issues more carefully. This seems closely related to https://github.com/photoshell/rawkit/issues/116.

**Comment by campaul** [comment]
I'll add this to my list of edge cases for re-working how libraw is loaded in. Going to make sure I have a solution that works for everything (including #116).

**Comment by SamWhited** [comment]
We do still need to do some work on the loader (eg. see #148), but this appears to have been fixed by https://hg.python.org/cpython/rev/385181e809bc

Closing this issue now, but let me know if anything is still broken.
