### ISSUE TITLE
metadata.orientation is not correct

### ISSUE THREAD

**Issue by kampde** [photoshell/rawkit#120]
My sample size is of only 1 image, sorry...

On this image http://img.photographyblog.com/reviews/nikon_d750/sample_images/nikon_d750_22.nef (from http://www.photographyblog.com/reviews/nikon_d750_review/sample_images/), the following code prints `orientation: 5`:

```
with Raw(filename='nikon.nef') as raw:                                                              
    orientation = raw.metadata.orientation                                                          
    print('orientation:', orientation)
```

while `exiftool -n -Orientation nikon.nef` returns `Orientation: 8`, which seems to be the correct value.

**Comment by campaul** [comment]
That link is returning a 403 for me. Do you have another link so I can look into this?

**Comment by kampde** [comment]
Hm maybe they are filtering by referer or something. I have uploaded the image to http://campderros.com/nikon.nef

**Comment by campaul** [comment]
Thanks, that worked. I'll start looking into the bug now.

**Comment by campaul** [comment]
After doing some research it looks like this isn't actually a bug. `libraw` and `exiftool` just use different numbering systems. `exiftool`'s 1, 3, 6, and 8 correspond to `libraw`'s 0, 3, 6, and 5 respectively.

| Needed Rotation | libraw | exiftool |
| --- | --- | --- |
| 0 | 0 | 1 |
| 90 CW | 6 | 6 |
| 180 CW | 3 | 3 |
| 270 CW | 5 | 8 |

I can add some constants with reasonable names so you don't have to deal with number codes. Something like `ROATE_90_CW` for example.

**Comment by kampde** [comment]
Quoting the [exif 2.3 specification](http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf):

    Orientation
    -----------
    The image orientation viewed in terms of rows and columns.

    Tag = 274 (112.H)
    Type = SHORT
    Count = 1
    Default = 1

    1 - The 0th row is at the visual top of the image, and the 0th
        column is the visual left-hand side.
    2 - The 0th row is at the visual top of the image, and the 0th
        column is the visual right-hand side.
    3 - The 0th row is at the visual bottom of the image, and the
        0th column is the visual right-hand side.
    4 - The 0th row is at the visual bottom of the image, and the
        0th column is the visual left-hand side.
    5 - The 0th row is the visual left-hand side of the image, and
        the 0th column is the visual top.
    6 - The 0th row is the visual right-hand side of the image,
        and the 0th column is the visual top.
    7 - The 0th row is the visual right-hand side of the image,
        and the 0th column is the visual bottom.
    8 - The 0th row is the visual left-hand side of the image, and
        the 0th column is the visual bottom.
    Other - reserved

There is a nice explanation with examples at http://www.impulseadventure.com/photo/exif-orientation.html

The value returned by `libraw` is called `flip`, and doesn't match the `Orientation` tag from exif metadata. I would suggest that `rawkit` follows the exif specification, or do not call that value `Orientation`, as it is misleading and wrong.

**Comment by campaul** [comment]
That sounds reasonable. I'll start working on a change to make `raw.metadata.orientation` reflect the Exif rotation values.

As a note for this change: `libraw` doesn't appear to have a concept of mirrored images, so we might need to add in separate Exif parsing to correctly handle images with orientation 2, 4, 5, or 7.

**Comment by campaul** [comment]
This is partially fixed now. Mirrored orientations don't work yet, but orientations 1, 3, 6, and 8 should be reported correctly.

**Comment by SamWhited** [comment]
By trial-and-error, the full map from libraw values to exif when setting `user_flip` is:

```python
exif_orientation_map = {
    # libraw: exif
    0: 1, # 0-deg
    1: 2, # 0-deg, mirror horizontal
    2: 4, # 0-deg, mirror vertical
    3: 3, # 180-deg
    4: 5, # 90ccw, mirror vertical
    5: 8, # 90ccw
    6: 6, # 90cw
    7: 7, # 90cw, mirror vertical
}
```

I have no idea if libraw reads the exif properly though or if this is a dcraw feature that only works if we set it ourselves.
