### ISSUE TITLE
error with Raw.color()

### ISSUE THREAD

**Issue by anielsen001** [photoshell/rawkit#138]
If I try to get the color of a pixel, I get a type error, requiring an integer. 

```
raw = Raw(filename='IMG_20180502_050956.dng')

raw.color(0,1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-e0cc1fb144e5> in <module>()
----> 1 raw.color(0,1)

//home/apn/sw/lib/python2.7/site-packages/rawkit/raw.pyc in color(self, y, x)
    202         """
    203         color_index = self.libraw.libraw_COLOR(self.data, y, x)
--> 204         return chr(self.color_description[color_index])
    205 
    206     @property

TypeError: an integer is required
> //home/apn/sw/lib/python2.7/site-packages/rawkit/raw.py(204)color()
    203         color_index = self.libraw.libraw_COLOR(self.data, y, x)
--> 204         return chr(self.color_description[color_index])
    205 
```

The issue seems to be that self.color_index  is a string and when indexed returns a single character string. In my example

```
In [39]: raw.color_description
Out[39]: 'RGBG'

In [40]: raw.color_description[0]
Out[40]: 'R'
```

The final return statement calls chr() on this value which returns the error because chr() expects an integer. The simple fix would be to remove the chr() function call before returning.  I am happy to do this an submit a PR, but I wanted to ask if maybe the chr() was used for another reason. 

I'm using Python 2.7.3, rawkit 0.6.0 (from pypi), libraw 0.17.1 with Ubuntu 16.04

**Comment by SamWhited** [comment]
This appears to be a Python 2/3 problem. On Python 3 this returns a byte string, eg. `b'RGBG'` so getting the first value gives uss a number and the `chr` is needed to go back to a string.
