### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by dunty** [photoshell/rawkit#142]
libraw already support windows, so pls add this capability.
maybe need:
1. download libraw win binary package and extract to some path.
https://www.libraw.org/data/LibRaw-0.18.13.zip
2. add this path to PATH. using ```setx -m PATH "$PATH$;....".
3. libraw.dll need ``` msvcr120.dll``` and ```msvcp120.dll```(can use Dependency Walker 2.2 to check). can download these dlls and copy to c:\windows\system32
4. update bindings.py:
in Win need ```libraw = util.find_library('raw')``` change to ```libraw = util.find_library('libraw')```.

**Comment by SamWhited** [comment]
Hi, thanks for your interest. None of the maintainers of this project are Windows users so I'm afraid we can't really support something like this. In addition, I'm not sure how we'd run CI with a Windows environment (though I'm open to suggestions if someone supports this). Outside of Linux distros or a few common BSD variants we wouldn't notice if support were to break, so even if support were added I'd be worried that it would be somewhat fragile.

All that being said, I'm not against it if a PR were to appear that wasn't too complicated, pending @campaul's approval, of course.

Could you detail what's broken right now, maybe that would give us a better idea of how to fix it? Your post makes it sound like it works with a bit of setup in which case I'm not sure what work there is for us to do?

**Comment by dunty** [comment]
Hi, thanks for your works and your answer, rawkit is a very good tool though that I can get camera data in a RAW file.
Yes, it works well after those setup steps. This issue is just a suggest, if you don't consider to support windows, that is ok. Others can reference this issue if they want use rawkit in windows.

**Comment by SamWhited** [comment]
I still don't quite understand what you wanted; were you asking for the procedure you outlined to be documented somewhere?

**Comment by SamWhited** [comment]
Ah, no, I see, you were wanting a change to `bindings.py`, I'm sure we'd accept a patch for that if you wanted to submit a PR.
