### ISSUE TITLE
Expose raw buffer

### ISSUE THREAD

**Issue by campaul** [photoshell/rawkit#19]

**Comment by SamWhited** [comment]
Is this not fixed by `to_buffer`, or was this issue about the original non-RGB data? Needs context.

**Comment by SamWhited** [comment]
@campaul ^^

**Comment by campaul** [comment]
This is referring to the not dcraw processed data.

**Comment by SamWhited** [comment]
I'm not sure that we need this; I think we should be the higher level API, this strikes me as a lower level thing (which you can get through the LibRaw API if you want to go down to that level).

**Comment by SamWhited** [comment]
I just had another change of heart on this; maybe we do want to support this, because if you're a researcher using photos to analyse something you probably want a way to get the raw bayer moire data (and you shouldn't have to dig down into libraw land to do it). I'll probably change my mind again tomorrow though.

**Comment by KelSolaar** [comment]
I pinged you about exactly that on FreeNode! I would actually need access to the non-debayered raw data (brut sensor data) that I would hook into Numpy arrays for further explorations.

**Comment by paalge** [comment]
Hi. This is very useful, but is there a way to expose the full Bayer matrix (RGGB)? This is the `-D` option in dcraw. Also with 16 bit enabled images each channel is split in two 8 bit images, is this intentional?

**Comment by SamWhited** [comment]
I still haven't gotten around to fixing this issue, sorry. I've messed with it a bit, but the LibRaw behavior is not well defined here and doesn't appear to match the docs. I'll ask around and see if I can't get it working this weekend.

**Comment by paalge** [comment]
No problem, I'll be glad to help if you want, as I was in the process of starting the implementation of a cpython interface with libraw when I found your module.

**Comment by SamWhited** [comment]
@paalge many thanks; pull requests are always welcome.

**Comment by paalge** [comment]
I've created a pull request #104 
By the way I think the reason that the 16 bit image becomes two 8 bit images is that the returned type is `ushort`, while `bytearray` assumes only one byte.
