### ISSUE TITLE
Setup pypi

### ISSUE THREAD

**Issue by campaul** [photoshell/rawkit#3]

**Comment by achennu** [comment]
Are you aware of the package picnic? https://pypi.python.org/pypi/picnic

This eases the creation of packages greatly. In this case it would require that the libraw dependancy is coded in somehow, but otherwise it should work.

**Comment by SamWhited** [comment]
That's pretty nifty; we've already got most everything it gives us for this project, but @campaul and I were just talking about eventually wanting a quicker way to bootstrap new projects. Thanks for the link.

**Comment by SamWhited** [comment]
0.1.0 now on PyPi: https://pypi.python.org/pypi/rawkit
