### ISSUE TITLE
ImportError: No module named bindings

### ISSUE THREAD

**Issue by ntim** [photoshell/rawkit#78]
Hi,

installed rawkit via pip on my Ubuntu 15.04 (stock Python 2.7.9) and libraw10. I get the following error:

```
>>> from rawkit.raw import Raw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rawkit/raw.py", line 8, in <module>
    from libraw.bindings import LibRaw
ImportError: No module named bindings
```
Executing
```
libraw.bindings import LibRaw
```
works fine.

Same happens on a scientific linux (python 2.7.10).

**Comment by SamWhited** [comment]
I suspect that I botched the egg/wheel build. Will check that both packages are actually being installed when I'm next at my desk.

**Comment by SamWhited** [comment]
Confirmed, works fine on Python 3, doesn't work on Pyton 2:

```python
$ python
Python 2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rawkit.raw import Raw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/src/rawkittest/venv/lib/python2.7/site-packages/rawkit/raw.py", line 8, in <module>
    from libraw.bindings import LibRaw
ImportError: No module named bindings
>>> from libraw.bindings import LibRaw
>>>
```

I'd still love to know what's going on, but as far as I'm concerned we shouldn't bother supporting Python 2. Any ideas @campaul?

**Comment by SamWhited** [comment]
Ah, I'm not sure why, but for some reason there's an old version of `rawkit.libraw`, which is breaking things (because it then sees libraw and tries to do a relative import of `rawkit.libraw.bindings...` no idea where PIP is getting this file, and can't really look until after work. Will advise.

**Comment by SamWhited** [comment]
A quick update: I'm now home, and found the problem. It should be prevented in future by 00011e174051b9b64d54943b8382b2b640399a1b, and 04dd49d1bd662b2b594588c8c03b5e367b554e18.

PyPi is currently broken (it's throwing a 500 on upload via setup.py and with their web form), but as soon as it comes up I'll cut a new release and mark this as resolved.

**Comment by SamWhited** [comment]
PyPi came back; let me know if the new release (0.3.0) works for you, and thanks for the bug report.

**Comment by ntim** [comment]
Works ;-)
