### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by campaul** [photoshell/rawkit#8]

**Comment by SamWhited** [comment]
Temporarily using [this](https://openclipart.org/detail/195036/rocket) as the logo in the docs. We can change it later when @campaul draws us something fancy with his mad art skills.
![rocket](https://cloud.githubusercontent.com/assets/512573/7826398/04c33944-03df-11e5-872b-563aa182319f.png)

**Comment by SamWhited** [comment]
Closing since it doesn't seem like we're going to get to this and the public domain one is fine.
