### ISSUE TITLE
Support multiple versions of libraw

### ISSUE THREAD

**Issue by campaul** [photoshell/rawkit#9]

**Comment by SamWhited** [comment]
I'm thinking we just need to support 0.16.x and start adding support for the new alpha version so that we can support 0.17 as soon as it's released.

**Comment by campaul** [comment]
I meant support adding multiple versions, not adding old versions in. Right now `libraw.so.10` is hard coded, so I just need to write some code to detect and select between versions.

**Comment by SamWhited** [comment]
Ah, gotcha. After work I was thinking about grabbing documentation, but that shouldn't take me too long in the current state, so I can probably hop on this too.

**Comment by SamWhited** [comment]
@campaul I'm thinking that the futher we push this off the more code we'll have to go back and fix to work with multiple versions. I still don't know what you had in mind for this; what's the work estimate like? Can we bump it to the 0.6 milestone, or do we want to leave it until 1.0 for some reason?

**Comment by campaul** [comment]
Moved to 0.5.0 because it's not actually that hard, it just needs to happen when no other big changes are going on.

**Comment by campaul** [comment]
If we need to support multiple versions of libraw we'll just support multiple versions of rawkit. We can keep a branch just for the old version and cherry pick high priority fixes, then just require getting a new version of libraw to get new features of rawkit.

**Comment by SamWhited** [comment]
:+1: Works for me; we should investigate how other things handle this (I suspect this way).
