### ISSUE TITLE
Support LibRaw 0.18

### ISSUE THREAD

**Issue by SamWhited** [photoshell/rawkit#93]
Update the `libraw` structs to support [LibRaw 0.18](http://www.libraw.org/news/libraw-0-18-201511) (or whatever the current version is when the structs are updated).

**Comment by guillaume65** [comment]
Sam,

Some questions:
The C-struct libraw_output_params_t contains the line:
` char **custom_camera_strings;`
I converted that into:
`('custom_camera_strings', POINTER(c_char_p)),`
Can you confirm this is correct?

I also modified the bindings.py file to contain the version 18 of libraw.

I will now look into testing the new version and contact you later on committing the changes.

Wim

**Comment by SamWhited** [comment]
> The C-struct libraw_output_params_t contains the line:
> ` char **custom_camera_strings;`
> I converted that into:
> `('custom_camera_strings', POINTER(c_char_p)),`

If `custom_camera_strings` is an array of null terminated strings that will be correct (I assume it is). If it can hold binary data you'd want `POINTER(POINTER(c_char))`. I think what you've got is probably right though.

**Comment by guillaume65** [comment]
I have no idea if this is correct, but if I run pytest, I get the following output:

`===================================== test session starts` `====================================`
`platform linux -- Python 3.5.2, pytest-3.0.7, py-1.4.33, pluggy-0.4.0`
`rootdir: /home/wim/Development/rawkit, inifile:`
`collected 53 items `

`tests/unit/bindings_test.py .......`
`tests/unit/options_test.py .................`
`tests/unit/raw_test.py ...........................`
`tests/unit/util_test.py ..`

`================================== 53 passed in 0.33 seconds` `==================================`

**Comment by SamWhited** [comment]
Nice! We don't actually have any good tests around the libraw parts of the libraries (we have basic unit tests, but no comprehensive tests that actually involve using libraw); maybe you could download a few random images from https://rawsamples.ch/ and try decoding them?

Feel free to submit a PR whenever and we can help tests / try to get it merged. Thanks again!

**Comment by guillaume65** [comment]
Ok, I forked the code added a structs_18.py file and added reference to the new file in bindings.py.
I ran the WhiteBalance example from the README file successfully.
I would appreciate if you could do some further testing.
I'm a bit of a Github noob, so I am not sure how to get the new files merged into the main branch.
Please let me know if I need to do something.

**Comment by SamWhited** [comment]
Thanks @guillaume65! Can you submit a pull request please and we'll look it over? Their help article is here if you want to read up on PR's: https://help.github.com/articles/about-pull-requests/

If that all sounds like a bit much (GitHub's process is a bit cumbersome sometimes), feel free to just paste a link to your branch or a diff here and I'll snag it and look it over.

**Comment by damonlynch** [comment]
Is there any update on the status of the new code? Thanks.

**Comment by SamWhited** [comment]
Travis is currently failing; I have not tested it yet.

**Comment by guillaume65** [comment]
Travis shows errors and warnings on files I haven't touched. I am not familiar enough with rawkit/travis to assist on this.

**Comment by SamWhited** [comment]
Ah, sorry about that, you're absolutely right; I'm not sure when CI broke, but I'll try to get it in working order this weekend sometime.

**Comment by damonlynch** [comment]
Hi, are there any plans to release a new version with @guillaume65 's patch? A new version supporting libraw 0.18.x would be extremely helpful for package maintainers making packages for Fedora, Debian, openSUSe etc.

**Comment by SamWhited** [comment]
Not at this time, I'd love to get this out, but I'm not currently working on this library and am not able to properly test this (or fix CI) right now. Sorry.

**Comment by campaul** [comment]
I'll get a new version sorted out this weekend.

@damonlynch is anyone actually maintaining packages for this? I'd love to know about it if they are.

**Comment by damonlynch** [comment]
Thanks @campaul! I'm not aware of any distro that currently packages rawkit. However, the latest version of my application Rapid Photo Downloader uses rawkit, so if the distros like Debian and Fedora continue to package Rapid Photo Downloader, then they'll also need to package rawkit.

**Comment by SamWhited** [comment]
Thanks @campaul; I've been avoiding this, but if you want to get together sometime this weekend and hash out a release let me know and I'll try and help.

**Comment by campaul** [comment]
This is done as of v0.6.0.

**Comment by damonlynch** [comment]
Looks like it's heading to Debian: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1530692.html
