### ISSUE TITLE
Set output file type based on filename

### ISSUE THREAD

**Issue by SamWhited** [photoshell/rawkit#94]
When calling `.save()` the default file type should be based on the filename (eg. if we do `raw.save(filename='somefile.tiff')` it should save a tiff file, not a ppm file).

**Comment by campaul** [comment]
As long as it only infers when a type isn't specified. As stupid as it sounds, users should be able to make a ppm with a tiff extension if they really want.

**Comment by SamWhited** [comment]
Agreed; my thoughts on what the behavior should look like are:

Use flietype if specified, otherwise set filetype to extension if available (will throw an invalid file type error if extension is something other than "tiff" or "ppm"), otherwise use "ppm".
