### ISSUE TITLE
File export broken

### ISSUE THREAD

**Issue by SamWhited** [photoshell/rawkit#95]
File export is currently broken; it will attempt to set `self.data.contents.params.output_tiff` to a string (`tiff` or `ppm`) instead of the expected boolean.

This might warrant an emergency patch and an extra test to check the default type.

**Comment by campaul** [comment]
Can you clarify "broken". I've been able to save files without issue. Is it just stuck in one format or something?

**Comment by SamWhited** [comment]
I'm not entirely sure when or why this changed (or how it's possible that I didn't notice it), but the file export property of LibRaw was being set to a string even though it should be an int (or a boolean), which was causing ctypes to throw an error. It might have been that it was ALWAYS saving to a PGM file before no matter what was specified, because we were just setting it to a string of `tiff` or `ppm` which was truthy and being massaged by ctypes to `1`. Just a guess.

Integration tests are needed...

Error:

```
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    raw.save(filename='test.tiff')
  File "/home/sam/Projects/rawkit/rawkit/raw.py", line 119, in save
    self.data.contents.params.output_tiff = filetype
TypeError: an integer is required (got type str)
```
